### ISSUE TITLE
emit() does not always call listeners

### ISSUE THREAD

**Issue by kanongil** [hapijs/podium#15]
With the current implementation a something like this won't emit everything, contrary to what the docs say:

```js
const Podium = require('podium');

const emitter = new Podium({
    name: 'test'
});

emitter.on({
    name: 'test',
    block: true,
}, (value, callback) => {

    console.log('test emitted');
    process.nextTick(callback);
});

emitter.emit('test');
emitter.emit('test');

emitter.removeAllListeners('test');
```

Output:
```
test emitted
```

Output without removing listeners:
```
test emitted
test emitted
```

I discovered this bug, since hapi can miss log lines, when stopping the server, after upgrading to `v15.x`.

**Comment by hueniverse** [comment]
Well, this is because you are not waiting for the second `emit()` callback to know it is done emitting before removing the listeners. I am going to revisit the usage of setImmediate and see if I can just go back to the original node behavior. I am closing this because if this is an issue in hapi logging, it is not because of podium but because of how podium is being used. If I keed the setImmediate, I might add a flush command.
